/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ballardtech_BTI429 */

#ifndef _Included_com_ballardtech_BTI429
#define _Included_com_ballardtech_BTI429
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDGetData
 * Signature: (JSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDGetData
  (JNIEnv *, jobject, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDGetMant
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDGetMant
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDGetSign
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_BCDGetSign
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDGetSSM
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_BCDGetSSM
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDGetVal
 * Signature: (Lballard/BTICard/StringRef;JSLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_BCDGetVal
  (JNIEnv *, jobject, jobject, jlong, jshort, jstring);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDPutData
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDPutData
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDPutMant
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDPutMant
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDPutSign
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDPutSign
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDPutSSM
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDPutSSM
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BCDPutVal
 * Signature: (Ljava/lang/String;JSLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BCDPutVal
  (JNIEnv *, jobject, jstring, jlong, jshort, jstring);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRGetData
 * Signature: (JSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRGetData
  (JNIEnv *, jobject, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRGetMant
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRGetMant
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRGetSign
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_BNRGetSign
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRGetSSM
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_BNRGetSSM
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRGetVal
 * Signature: (Lballard/BTICard/StringRef;JSLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_BNRGetVal
  (JNIEnv *, jobject, jobject, jlong, jshort, jstring);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRPutData
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRPutData
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRPutMant
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRPutMant
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRPutSign
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRPutSign
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRPutSSM
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRPutSSM
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    BNRPutVal
 * Signature: (Ljava/lang/String;JSLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_BNRPutVal
  (JNIEnv *, jobject, jstring, jlong, jshort, jstring);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChClear
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ChClear
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChConfig
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ChConfig
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChGetCount
 * Signature: (Lballard/BTICard/IntRef;Lballard/BTICard/IntRef;I)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_ChGetCount
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChGetInfo
 * Signature: (SII)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_ChGetInfo
  (JNIEnv *, jobject, jshort, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChIs429
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ChIs429
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChIsRcv
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ChIsRcv
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChIsXmt
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ChIsXmt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChPause
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_ChPause
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChPauseCheck
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ChPauseCheck
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChResume
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_ChResume
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChStart
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ChStart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChStop
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ChStop
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChSyncDefine
 * Signature: (ZSSII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ChSyncDefine
  (JNIEnv *, jobject, jboolean, jshort, jshort, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ChTriggerDefine
 * Signature: (ZSSSII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ChTriggerDefine
  (JNIEnv *, jobject, jboolean, jshort, jshort, jshort, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    CmdAddr
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_CmdAddr
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    CmdCountRd
 * Signature: (II)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_CmdCountRd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    CmdRd
 * Signature: ([CII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_CmdRd
  (JNIEnv *, jobject, jcharArray, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FilterClear
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_FilterClear
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FilterDefault
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_FilterDefault
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FilterRd
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_FilterRd
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FilterSet
 * Signature: (IISII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_FilterSet
  (JNIEnv *, jobject, jint, jint, jshort, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FilterWr
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_FilterWr
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldGetData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldGetData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldGetLabel
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_FldGetLabel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldGetParity
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_FldGetParity
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldGetSDI
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_com_ballardtech_BTI429_FldGetSDI
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldGetValue
 * Signature: (JSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldGetValue
  (JNIEnv *, jobject, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldPutData
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldPutData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldPutLabel
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldPutLabel
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldPutSDI
 * Signature: (JS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldPutSDI
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    FldPutValue
 * Signature: (JJSS)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_FldPutValue
  (JNIEnv *, jobject, jlong, jlong, jshort, jshort);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListAsyncCreate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ListAsyncCreate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListDataRd
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_ListDataRd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListDataWr
 * Signature: (JII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_ListDataWr
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListRcvCreate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ListRcvCreate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ListStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ListXmtCreate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ListXmtCreate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgBlockRd
 * Signature: (Lballard/BTI429/MSGFIELDS429;II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_MsgBlockRd
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgBlockWr
 * Signature: (Lballard/BTI429/MSGFIELDS429;II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_MsgBlockWr
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgCreate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_MsgCreate
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgDataRd
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_ballardtech_BTI429_MsgDataRd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgDataWr
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_MsgDataWr
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgGroupRd
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_MsgGroupRd
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgGroupWr
 * Signature: ([I[III)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_MsgGroupWr
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgIsAccessed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_MsgIsAccessed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgSkipRd
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ballardtech_BTI429_MsgSkipRd
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgSkipWr
 * Signature: (ZII)V
 */
JNIEXPORT void JNICALL Java_com_ballardtech_BTI429_MsgSkipWr
  (JNIEnv *, jobject, jboolean, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgSyncDefine
 * Signature: (ZCCII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_MsgSyncDefine
  (JNIEnv *, jobject, jboolean, jchar, jchar, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    MsgTriggerDefine
 * Signature: (ZCCCII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_MsgTriggerDefine
  (JNIEnv *, jobject, jboolean, jchar, jchar, jchar, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ParamAmplitudeConfig
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ParamAmplitudeConfig
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ParamAmplitudeGet
 * Signature: (Lballard/BTICard/IntRef;II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ParamAmplitudeGet
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ParamBitRateConfig
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ParamBitRateConfig
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    ParamBitRateGet
 * Signature: (Lballard/BTICard/IntRef;II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_ParamBitRateGet
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedBranch
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedBranch
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedBranchUpdate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedBranchUpdate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedBuild
 * Signature: (I[I[I[III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedBuild
  (JNIEnv *, jobject, jint, jintArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedCall
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedCall
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedCallUpdate
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedCallUpdate
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedEntry
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedEntry
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedGap
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedGap
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedGapFixed
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedGapFixed
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedGapList
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedGapList
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedHalt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedHalt
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedLog
 * Signature: (ICII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedLog
  (JNIEnv *, jobject, jint, jchar, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedMsg
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedMsg
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedMsgEx
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedMsgEx
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedPause
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedPause
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedPulse
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedPulse
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedRestart
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedRestart
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ballardtech_BTI429
 * Method:    SchedReturn
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ballardtech_BTI429_SchedReturn
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
